// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKE44_69nvAwOGdqm06euojgPUpFFeOh4',
    appId: '1:261201240665:web:78164064be8f1634d28748',
    messagingSenderId: '261201240665',
    projectId: 'hattabio-52afb',
    authDomain: 'hattabio-52afb.firebaseapp.com',
    storageBucket: 'hattabio-52afb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV1JB3xF2g_P1DCbZO3L0QYsi-sGrild4',
    appId: '1:261201240665:android:fb8cdd51e72a3705d28748',
    messagingSenderId: '261201240665',
    projectId: 'hattabio-52afb',
    storageBucket: 'hattabio-52afb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8DbAvBho5YVt_cJhVQ_palmSVVbGKgFU',
    appId: '1:261201240665:ios:3f3db123ff1ec688d28748',
    messagingSenderId: '261201240665',
    projectId: 'hattabio-52afb',
    storageBucket: 'hattabio-52afb.appspot.com',
    iosClientId: '261201240665-fc265j1hs59c4t5rj0bri38gi1agb5rr.apps.googleusercontent.com',
    iosBundleId: 'com.HATTA.BIO',
  );
}
